### PR TITLE
feat: cosmjs #ntrn-269

### PR DESCRIPTION
**Pull request by NeverHappened**
- cosmosclient to cosmjs migration
- removes old generated proto files in favor of cosmjs types (including newly generated repo for neutron)
- removes sequence retries for execTx (just use different wallets for each parallel test to avoid collisions)
- move over cosmos local state class to this repo
- increment node version to >= 20
- lots of small stuff

PR's:
- [neutron-integration-tests](https://github.com/neutron-org/neutron-integration-tests/pull/286)
  - cosmjs migration and more
- [neutronjsplus](https://github.com/neutron-org/neutronjsplus/pull/35)
  - cosmjs migration and more; remove old proto types
- [neutron-tests](https://github.com/neutron-org/neutron-tests/pull/10)
  - increment node version to >= 20
-  [neutron](https://github.com/neutron-org/neutron/pull/512)
   - because dao_assert tests break of not matching contracts

What to look at!
- rewriten localState and moved to the neutron-integration-tests (old name TestStateLocalCosmosTestNet)
- use SigningCosmWasmClient inside of WalletWrapper because it already has function for both execTx and cosmwasm methods (store, instantiate, executeContract)
- parallel integration tests now determine their index in the tests so that they can fetch their own wallets with money and run in parallel without clashing sequences
- now we have a separate repo https://github.com/neutron-org/cosmjs-types with generated types and clients for rpc queries/txs. It requires more changes to be other users ready (so that code for all modules are generated, correct versions for v4 neutron), but already works fine.

### CODE REVIEW

**Comment by NeverHappened** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/8993085461

**Comment by NeverHappened** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/9008635184

**Comment by NeverHappened** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/9114703647

**Comment by NeverHappened** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/9616294522

**Comment by NeverHappened** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/10201636953

**Review by pr0n00gler — DISMISSED** [review]

**Review by pr0n00gler — APPROVED** [review]

**Review by quasisamurai — APPROVED** [review]

**Pull request merged**
