### PR TITLE
 fix failures fields NTRN-359

### PR DESCRIPTION
**Pull request by quasisamurai**
[TASK](https://hadronlabs.atlassian.net/browse/NTRN-359)

### CODE REVIEW

**Review by NeverHappened — DISMISSED** [review]
please fix conflicts, otherwise LGTM

**Comment by quasisamurai** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/10351388273

**Comment by quasisamurai** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/10584317289

TESTRUN

**Review by NeverHappened — DISMISSED** [review]

**Comment by quasisamurai** [comment]
√ https://github.com/neutron-org/neutron-tests/actions/runs/10694686342

**Pull request merged**
